### ISSUE TITLE
Error on retrieving all names from metric collector details (Analizo)

### ISSUE THREAD

**Issue by diegoamc** [mezuro/kalibro_processor#168]
When trying to request the `MetricCollectorDetails#all_names` an error is raised for Analizo.
Check the error output.

```
/home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/source/git.rb:191:in `rescue in load_spec_files': https://github.com/mezuro/kolekti_analizo (at master) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/source/git.rb:188:in `load_spec_files'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/source/path.rb:92:in `local_specs'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/source/git.rb:159:in `specs'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/lazy_specification.rb:53:in `__materialize__'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/spec_set.rb:88:in `block in materialize'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /home/diego/.rvm/gems/ruby-2.2.3@kalibro_processor/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
	from /home/diego/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/diego/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
The error remains even after running `bundle install`.

**Comment by marcheing** [comment]
Related to issue 166

It works with KalibroConfigurations v1.2.5, but not after (this PR)[https://github.com/mezuro/kalibro_configurations/pull/72]

**Comment by rafamanzo** [comment]
Fixed by https://github.com/mezuro/kalibro_processor/commit/b8c5b1acb5ae4ebd87ddae11deccbfa1dd695bdb
